package com.csvfv.batch;

import java.util.Date;

public class RealisasiEntity {

    private  Integer id ;
    private  Integer created_by ;
    private  Integer updated_by ;
    private Date created_date ;
    private  Date updated_date ;
    private  String status ;
    private  String respon_status ;
    private  String keterangan_gagal ;
    private  String no_aplikasi ;
    private  String nama_debitur ;
    private  String jenis_debitur ;
    private  String gender_cd ;
    private  String nik ;
    private  String npwp ;
    private  String alamat ;
    private  String kelurahan ;
    private  String kecamatan ;
    private  String kodepos ;
    private  String dati2 ;
    private  String provinsi ;
    private  String no_telp ;
    private  String no_hp ;
    private  String email ;
    private  String tempat_lahir ;
    private  Date tgl_lahir ;
    private  String gelar_debitur_cd ;
    private  String tempat_bekerja ;
    private  String alamat_tempat_bekerja ;
    private  String nama_ibu_kandung ;
    private  String agama_cd ;
    private  Double penghasilan_per_bulan ;
    private  String status_perkawinan_cd ;
    private  String nama_pasangan ;
    private  Date tgl_lahir_pasangan ;
    private  String pisah_harta ;
    private  String no_akte ;
    private  Date tgl_berdiri ;
    private  String no_akte_terakhir ;
    private  Date tgl_akte_terakhir ;
    private  String bidang_usaha_cd ;
    private  Integer jangka_waktu ;
    private  String jenis_kredit_cd ;
    private  Double plafon ;
    private  Double suku_bunga ;
    private  String nomor_pk ;
    private  Date tgl_akad ;
    private  Date tgl_angsuran_1 ;
    private  String jenis_penggunaan_cd ;
    private  String sektor_ekonomi_cd ;
    private  Double omzet ;
    private  String go_public_cd ;
    private  String golongan_debitur_cd ;
    private  Double penghasilan_per_tahun ;
    private  String bentuk_badan_cd ;
    private  String tempat_berdiri_badan ;
    private  Double original_amount ;
    private  Date tgl_disbursement ;
    private  Integer tenor ;
    private  String segmentasi_debitur_cd ;
    private  String pekerjaan_cd ;
    private  String debtor_category_cd ;
    private  String sumber_penghasilan_cd ;
    private  Integer jumlah_tanggungan ;

    public RealisasiEntity(Integer id, Integer created_by, Integer updated_by, Date created_date, Date updated_date, String status, String respon_status, String keterangan_gagal, String no_aplikasi, String nama_debitur, String jenis_debitur, String gender_cd, String nik, String npwp, String alamat, String kelurahan, String kecamatan, String kodepos, String dati2, String provinsi, String no_telp, String no_hp, String email, String tempat_lahir, Date tgl_lahir, String gelar_debitur_cd, String tempat_bekerja, String alamat_tempat_bekerja, String nama_ibu_kandung, String agama_cd, Double penghasilan_per_bulan, String status_perkawinan_cd, String nama_pasangan, Date tgl_lahir_pasangan, String pisah_harta, String no_akte, Date tgl_berdiri, String no_akte_terakhir, Date tgl_akte_terakhir, String bidang_usaha_cd, Integer jangka_waktu, String jenis_kredit_cd, Double plafon, Double suku_bunga, String nomor_pk, Date tgl_akad, Date tgl_angsuran_1, String jenis_penggunaan_cd, String sektor_ekonomi_cd, Double omzet, String go_public_cd, String golongan_debitur_cd, Double penghasilan_per_tahun, String bentuk_badan_cd, String tempat_berdiri_badan, Double original_amount, Date tgl_disbursement, Integer tenor, String segmentasi_debitur_cd, String pekerjaan_cd, String debtor_category_cd, String sumber_penghasilan_cd, Integer jumlah_tanggungan) {
        this.id = id;
        this.created_by = created_by;
        this.updated_by = updated_by;
        this.created_date = created_date;
        this.updated_date = updated_date;
        this.status = status;
        this.respon_status = respon_status;
        this.keterangan_gagal = keterangan_gagal;
        this.no_aplikasi = no_aplikasi;
        this.nama_debitur = nama_debitur;
        this.jenis_debitur = jenis_debitur;
        this.gender_cd = gender_cd;
        this.nik = nik;
        this.npwp = npwp;
        this.alamat = alamat;
        this.kelurahan = kelurahan;
        this.kecamatan = kecamatan;
        this.kodepos = kodepos;
        this.dati2 = dati2;
        this.provinsi = provinsi;
        this.no_telp = no_telp;
        this.no_hp = no_hp;
        this.email = email;
        this.tempat_lahir = tempat_lahir;
        this.tgl_lahir = tgl_lahir;
        this.gelar_debitur_cd = gelar_debitur_cd;
        this.tempat_bekerja = tempat_bekerja;
        this.alamat_tempat_bekerja = alamat_tempat_bekerja;
        this.nama_ibu_kandung = nama_ibu_kandung;
        this.agama_cd = agama_cd;
        this.penghasilan_per_bulan = penghasilan_per_bulan;
        this.status_perkawinan_cd = status_perkawinan_cd;
        this.nama_pasangan = nama_pasangan;
        this.tgl_lahir_pasangan = tgl_lahir_pasangan;
        this.pisah_harta = pisah_harta;
        this.no_akte = no_akte;
        this.tgl_berdiri = tgl_berdiri;
        this.no_akte_terakhir = no_akte_terakhir;
        this.tgl_akte_terakhir = tgl_akte_terakhir;
        this.bidang_usaha_cd = bidang_usaha_cd;
        this.jangka_waktu = jangka_waktu;
        this.jenis_kredit_cd = jenis_kredit_cd;
        this.plafon = plafon;
        this.suku_bunga = suku_bunga;
        this.nomor_pk = nomor_pk;
        this.tgl_akad = tgl_akad;
        this.tgl_angsuran_1 = tgl_angsuran_1;
        this.jenis_penggunaan_cd = jenis_penggunaan_cd;
        this.sektor_ekonomi_cd = sektor_ekonomi_cd;
        this.omzet = omzet;
        this.go_public_cd = go_public_cd;
        this.golongan_debitur_cd = golongan_debitur_cd;
        this.penghasilan_per_tahun = penghasilan_per_tahun;
        this.bentuk_badan_cd = bentuk_badan_cd;
        this.tempat_berdiri_badan = tempat_berdiri_badan;
        this.original_amount = original_amount;
        this.tgl_disbursement = tgl_disbursement;
        this.tenor = tenor;
        this.segmentasi_debitur_cd = segmentasi_debitur_cd;
        this.pekerjaan_cd = pekerjaan_cd;
        this.debtor_category_cd = debtor_category_cd;
        this.sumber_penghasilan_cd = sumber_penghasilan_cd;
        this.jumlah_tanggungan = jumlah_tanggungan;
    }
}
